import express from 'express';
import Database from 'better-sqlite3';
import webpush from 'web-push';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const app=express();app.use(express.json());app.use(express.static(path.join(__dirname,'public')));
const db=new Database(process.env.DATABASE_PATH||path.join(__dirname,'data.sqlite'));db.exec(`CREATE TABLE IF NOT EXISTS kv(k TEXT PRIMARY KEY,v TEXT NOT NULL);CREATE TABLE IF NOT EXISTS pushes(endpoint TEXT PRIMARY KEY,v TEXT NOT NULL)`);
const get=k=>{const r=db.prepare('SELECT v FROM kv WHERE k=?').get(k);return r?JSON.parse(r.v):null},set=(k,v)=>db.prepare('INSERT INTO kv(k,v) VALUES(?,?) ON CONFLICT(k) DO UPDATE SET v=excluded.v').run(k,JSON.stringify(v));
let vapid=get('vapid');if(!vapid){vapid=webpush.generateVAPIDKeys();set('vapid',vapid)}webpush.setVapidDetails(process.env.VAPID_SUBJECT||'mailto:vab5-monitor@example.com',vapid.publicKey,vapid.privateKey);
const defaults={minDelayMinutes:2,notifyOnlyOnChange:true,pollingSeconds:300,windows:[{id:'morning',enabled:true,days:[1,2,3,4,5,6,7],start:'06:00',end:'09:30',direction:'OUTBOUND'},{id:'evening',enabled:true,days:[1,2,3,4,5,6,7],start:'16:00',end:'18:30',direction:'INBOUND'}]};
const settings=()=>get('settings')||defaults,state=()=>get('state')||{};
const cfg={endpoint:process.env.OEBB_HAFAS_ENDPOINT||'https://fahrplan.oebb.at/bin/mgate.exe',aid:process.env.OEBB_HAFAS_AID||'OWDL4fE4ixNiPBBm',version:process.env.OEBB_HAFAS_VERSION||'1.45',port:Number(process.env.PORT||8787),tz:'Europe/Vienna'};
async function hafas(svcReqL){const body={id:'1',ver:cfg.version,lang:'de',auth:{type:'AID',aid:cfg.aid},client:{id:'OEBB',type:'IPH',name:'oebbPROD-ADHOC',l:'de'},formatted:false,svcReqL};const r=await fetch(cfg.endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error(`ÖBB HTTP ${r.status}`);return r.json()}
let stationCache={};async function station(name){const k=name.toLowerCase();if(stationCache[k])return stationCache[k];const d=await hafas([{meth:'LocMatch',req:{input:{field:'S',loc:{name,type:'ALL'},maxLoc:8}}}]);const a=d?.svcResL?.[0]?.res?.match?.locL||[];const p=a.find(x=>String(x.name||'').toLowerCase().includes(k))||a[0];if(!p)throw Error(`Station nicht gefunden: ${name}`);return stationCache[k]={lid:p.lid,name:p.name,extId:p.extId}}
const isoDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:cfg.tz,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()).replaceAll('-','');
const isoTime=()=>new Intl.DateTimeFormat('en-GB',{timeZone:cfg.tz,hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date()).replaceAll(':','');
const fmt=(date,t)=>`${date.slice(0,4)}-${date.slice(4,6)}-${date.slice(6,8)}T${t.slice(0,2)}:${t.slice(2,4)}:${t.slice(4,6)||'00'}+02:00`;
function parsed(j,prod,date){const s=j.stbStop||{},p=s.dTimeS||s.aTimeS,r=s.dTimeR||s.aTimeR||null;const delay=p&&r?Math.round((new Date(fmt(date,r))-new Date(fmt(date,p)))/60000):null;return {tripId:j.jnyId||j.id||null,line:prod?.name||'',direction:j.dirTxt||'',plannedDeparture:fmt(date,p),realtimeDeparture:r?fmt(date,r):null,delaySeconds:delay==null?null:delay*60,status:j.cancelled||s.cancelled?'CANCELLED':delay==null?'NO_REALTIME':delay>0?'DELAYED':'ON_TIME',platform:s.dPltfS?.txt||s.aPltfS?.txt||null}}
async function board(direction){const st=await station(direction==='OUTBOUND'?'Wien Praterstern':'Flughafen Wien');const d=await hafas([{meth:'StationBoard',req:{stbLoc:{lid:st.lid,type:'S'},date:isoDate(),time:isoTime(),type:'DEP',maxJny:30}}]);const r=d?.svcResL?.[0]?.res||{},ps=r.common?.prodL||[],js=r.jnyL||[],date=r.date||isoDate();return js.map(j=>parsed(j,ps[j.prodX],date)).filter(x=>{const l=x.line.toUpperCase(),q=x.direction.toUpperCase();return /VAB\s*5|VAB5/.test(l)&&(direction==='OUTBOUND'?/FLUGHAFEN|AIRPORT|VIE/.test(q):/PRATERSTERN/.test(q));}).sort((a,b)=>new Date(a.plannedDeparture)-new Date(b.plannedDeparture))}
async function current(direction){const a=await board(direction),now=Date.now();return {departures:a.filter(x=>new Date(x.plannedDeparture).getTime()>now-120000).slice(0,5),fetchedAt:new Date().toISOString(),source:'ÖBB HAFAS'}}
function dayMin(){const p=new Intl.DateTimeFormat('en-GB',{timeZone:cfg.tz,weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date()),o=Object.fromEntries(p.map(x=>[x.type,x.value])),m={Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6,Sun:7};return {day:m[o.weekday],min:+o.hour*60 + +o.minute}}
const toMin=s=>{const [h,m]=s.split(':').map(Number);return h*60+m};
function active(dir){const d=dayMin();return settings().windows.find(w=>w.enabled&&w.direction===dir&&(w.days||[]).includes(d.day)&&d.min>=toMin(w.start)&&d.min<=toMin(w.end))}
app.get('/api/settings',(q,res)=>res.json(settings()));
app.put('/api/settings',(req,res)=>{if(!Array.isArray(req.body?.windows))return res.status(400).json({error:'invalid settings'});set('settings',{...settings(),...req.body});res.json(settings())});
app.get('/api/status',async(req,res)=>{try{res.json(await current(req.query.direction==='INBOUND'?'INBOUND':'OUTBOUND'))}catch(e){res.status(502).json({error:e.message})}});
app.get('/api/push/config',(q,res)=>res.json({enabled:true,publicKey:vapid.publicKey}));
app.post('/api/push/subscribe',(req,res)=>{const s=req.body;if(!s?.endpoint||!s?.keys)return res.status(400).json({error:'invalid subscription'});db.prepare('INSERT INTO pushes(endpoint,v) VALUES(?,?) ON CONFLICT(endpoint) DO UPDATE SET v=excluded.v').run(s.endpoint,JSON.stringify(s));res.json({ok:true})});
async function notify(s,dir){const mins=s.delaySeconds==null?null:Math.round(s.delaySeconds/60);const msg=s.status==='CANCELLED'?`VAB 5 ${dir==='OUTBOUND'?'Praterstern → Flughafen':'Flughafen → Praterstern'}\nAUSFALL`:mins==null?`VAB 5\nKeine Echtzeitdaten · Soll ${new Date(s.plannedDeparture).toLocaleTimeString('de-AT',{hour:'2-digit',minute:'2-digit'})}`:`VAB 5 ${mins<=0?'pünktlich':'+'+mins+' min'}\n${dir==='OUTBOUND'?'Praterstern → Flughafen':'Flughafen → Praterstern'} · ${new Date(s.realtimeDeparture||s.plannedDeparture).toLocaleTimeString('de-AT',{hour:'2-digit',minute:'2-digit'})}`;for(const row of db.prepare('SELECT endpoint,v FROM pushes').all()){try{await webpush.sendNotification(JSON.parse(row.v),JSON.stringify({title:'VAB 5 Monitor',body:msg}))}catch(e){if([404,410].includes(e.statusCode))db.prepare('DELETE FROM pushes WHERE endpoint=?').run(row.endpoint)}}}
async function run(force=false){const out=[];for(const dir of ['OUTBOUND','INBOUND']){if(!force&&!active(dir))continue;try{const x=await current(dir),s=x.departures?.[0];if(!s){out.push({direction:dir,status:'NO_DEPARTURE'});continue}const st=state(),today=new Intl.DateTimeFormat('en-CA',{timeZone:cfg.tz}).format(new Date()),p=st[dir],mins=s.delaySeconds==null?null:Math.round(s.delaySeconds/60),sig=!p||p.tripId!==s.tripId||p.status!==s.status||(mins!=null&&mins>=settings().minDelayMinutes);if(!p||p.day!==today||sig&&!settings().notifyOnlyOnChange){await notify(s,dir);st[dir]={day:today,tripId:s.tripId,status:s.status};set('state',st)}out.push(s)}catch(e){out.push({direction:dir,error:e.message})}}return out}
setInterval(()=>run(false).catch(()=>{}),60000);
app.post('/api/monitor/run',async(q,res)=>{try{res.json(await run(true))}catch(e){res.status(502).json({error:e.message})}});
app.get('*',(q,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.listen(cfg.port,()=>console.log(`VAB5 Monitor on ${cfg.port}`));
