import express from 'express';
import webpush from 'web-push';
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
const __dirname=path.dirname(fileURLToPath(import.meta.url));const stateFile=process.env.STATE_FILE||path.join(__dirname,'data.json');
const defaults={settings:{minDelayMinutes:2,notifyOnlyOnChange:true,pollingSeconds:300,windows:[{id:'morning',enabled:true,days:[1,2,3,4,5,6,7],start:'06:00',end:'09:30',direction:'OUTBOUND'},{id:'evening',enabled:true,days:[1,2,3,4,5,6,7],start:'16:00',end:'18:30',direction:'INBOUND'}]},last:{},pushes:[],vapid:null};
function load(){try{return {...defaults,...JSON.parse(fs.readFileSync(stateFile,'utf8'))}}catch{return {...defaults}}}function save(s){fs.writeFileSync(stateFile,JSON.stringify(s,null,2))}
let db=load();if(!db.vapid){db.vapid=webpush.generateVAPIDKeys();save(db)}webpush.setVapidDetails(process.env.VAPID_SUBJECT||'mailto:vab5-monitor@example.com',db.vapid.publicKey,db.vapid.privateKey);
const app=express();app.use(express.json());app.use(express.static(path.join(__dirname,'public')));
const cfg={endpoint:process.env.OEBB_HAFAS_ENDPOINT||'https://fahrplan.oebb.at/bin/mgate.exe',aid:process.env.OEBB_HAFAS_AID||'OWDL4fE4ixNiPBBm',version:process.env.OEBB_HAFAS_VERSION||'1.45',port:Number(process.env.PORT||8787),tz:'Europe/Vienna'};
async function hafas(svcReqL){const body={id:'1',ver:cfg.version,lang:'de',auth:{type:'AID',aid:cfg.aid},client:{id:'OEBB',type:'IPH',name:'oebbPROD-ADHOC',l:'de'},formatted:false,svcReqL};const r=await fetch(cfg.endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error(`ÖBB HTTP ${r.status}`);return r.json()}
let stationCache={};async function station(name){const k=name.toLowerCase();if(stationCache[k])return stationCache[k];const d=await hafas([{meth:'LocMatch',req:{input:{field:'S',loc:{name,type:'ALL'},maxLoc:8}}}]);const a=d?.svcResL?.[0]?.res?.match?.locL||[];const p=a.find(x=>String(x.name||'').toLowerCase().includes(k))||a[0];if(!p)throw Error(`Station nicht gefunden: ${name}`);return stationCache[k]={lid:p.lid,name:p.name,extId:p.extId}}
function partsNow(){return Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:cfg.tz,weekday:'short',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).formatToParts(new Date()).map(x=>[x.type,x.value]))}
const isoDate=()=>{const o=partsNow();return `${o.year}${o.month}${o.day}`};const isoTime=()=>{const o=partsNow();return `${o.hour}${o.minute}${o.second}`};
function parseHafasDateTime(d,t){if(!t)return null;const y=+d.slice(0,4),m=+d.slice(4,6)-1,day=+d.slice(6,8),h=+t.slice(0,2),mi=+t.slice(2,4),s=+(t.slice(4,6)||0);const local=new Date(Date.UTC(y,m,day,h,mi,s));const guess=new Date(local.toLocaleString('en-US',{timeZone:cfg.tz}));const offset=local.getTime()-guess.getTime();return new Date(local.getTime()+offset).toISOString()}
function parsed(j,p,d){const s=j.stbStop||{},a=s.dTimeS||s.aTimeS,r=s.dTimeR||s.aTimeR||null;const pa=parseHafasDateTime(d,a),ra=parseHafasDateTime(d,r);const delay=pa&&ra?Math.round((Date.parse(ra)-Date.parse(pa))/60000):null;return{tripId:j.jnyId||j.id||null,line:p?.name||'',direction:j.dirTxt||'',plannedDeparture:pa,realtimeDeparture:ra,delaySeconds:delay==null?null:delay*60,status:j.cancelled||s.cancelled?'CANCELLED':delay==null?'NO_REALTIME':delay>0?'DELAYED':'ON_TIME',platform:s.dPltfS?.txt||s.aPltfS?.txt||null}}
async function board(direction){const st=await station(direction==='OUTBOUND'?'Wien Praterstern':'Flughafen Wien');const d=await hafas([{meth:'StationBoard',req:{stbLoc:{lid:st.lid,type:'S'},date:isoDate(),time:isoTime(),type:'DEP',maxJny:30}}]);const r=d?.svcResL?.[0]?.res||{},ps=r.common?.prodL||[],js=r.jnyL||[],date=r.date||isoDate();return js.map(j=>parsed(j,ps[j.prodX],date)).filter(x=>{const l=x.line.toUpperCase(),q=x.direction.toUpperCase();return /VAB\s*5|VAB5/.test(l)&&(direction==='OUTBOUND'?/FLUGHAFEN|AIRPORT|VIE/.test(q):/PRATERSTERN/.test(q));}).sort((a,b)=>Date.parse(a.plannedDeparture)-Date.parse(b.plannedDeparture))}
async function current(direction){const a=await board(direction),n=Date.now();return{departures:a.filter(x=>Date.parse(x.plannedDeparture)>n-120000).slice(0,5),fetchedAt:new Date().toISOString(),source:'ÖBB HAFAS'}}
function dayMin(){const o=partsNow(),m={Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6,Sun:7};return{day:m[o.weekday],min:+o.hour*60+ +o.minute}}
const toMin=s=>{const[h,m]=s.split(':').map(Number);return h*60+m};function active(dir){const d=dayMin();return db.settings.windows.find(w=>w.enabled&&w.direction===dir&&(w.days||[]).includes(d.day)&&d.min>=toMin(w.start)&&d.min<=toMin(w.end))}
app.get('/api/settings',(q,r)=>r.json(db.settings));app.put('/api/settings',(q,r)=>{if(!Array.isArray(q.body?.windows))return r.status(400).json({error:'invalid settings'});db.settings={...db.settings,...q.body};save(db);r.json(db.settings)});
app.get('/api/status',async(q,r)=>{try{r.json(await current(q.query.direction==='INBOUND'?'INBOUND':'OUTBOUND'))}catch(e){r.status(502).json({error:e.message})}});app.get('/api/push/config',(q,r)=>r.json({enabled:true,publicKey:db.vapid.publicKey}));
app.post('/api/push/subscribe',(q,r)=>{const s=q.body;if(!s?.endpoint||!s?.keys)return r.status(400).json({error:'invalid subscription'});db.pushes=db.pushes.filter(x=>x.endpoint!==s.endpoint);db.pushes.push(s);save(db);r.json({ok:true})});
async function notify(s,dir){const m=s.delaySeconds==null?null:Math.round(s.delaySeconds/60);const msg=s.status==='CANCELLED'?`VAB 5 ${dir==='OUTBOUND'?'Praterstern → Flughafen':'Flughafen → Praterstern'}\nAUSFALL`:m==null?`VAB 5\nKeine Echtzeitdaten · Soll ${new Date(s.plannedDeparture).toLocaleTimeString('de-AT',{hour:'2-digit',minute:'2-digit'})}`:`VAB 5 ${m<=0?'pünktlich':'+'+m+' min'}\n${dir==='OUTBOUND'?'Praterstern → Flughafen':'Flughafen → Praterstern'} · ${new Date(s.realtimeDeparture||s.plannedDeparture).toLocaleTimeString('de-AT',{hour:'2-digit',minute:'2-digit'})}`;for(const p of db.pushes){try{await webpush.sendNotification(p,JSON.stringify({title:'VAB 5 Monitor',body:msg}))}catch(e){if([404,410].includes(e.statusCode))db.pushes=db.pushes.filter(x=>x.endpoint!==p.endpoint)}}save(db)}
async function run(force=false){const out=[];for(const dir of ['OUTBOUND','INBOUND']){if(!force&&!active(dir))continue;try{const x=await current(dir),s=x.departures?.[0];if(!s){out.push({direction:dir,status:'NO_DEPARTURE'});continue}const today=new Intl.DateTimeFormat('en-CA',{timeZone:cfg.tz}).format(new Date()),p=db.last[dir],mins=s.delaySeconds==null?null:Math.round(s.delaySeconds/60),sig=!p||p.day!==today||p.tripId!==s.tripId||p.status!==s.status||(mins!=null&&mins>=db.settings.minDelayMinutes);if(sig){await notify(s,dir);db.last[dir]={day:today,tripId:s.tripId,status:s.status};save(db)}out.push(s)}catch(e){out.push({direction:dir,error:e.message})}}return out}
app.post('/api/monitor/run',async(q,r)=>{try{r.json(await run(true))}catch(e){r.status(502).json({error:e.message})}});setInterval(()=>run(false).catch(()=>{}),60000);
app.use((q,r)=>r.sendFile(path.join(__dirname,'public','index.html')));app.listen(cfg.port,()=>console.log(`VAB5 Monitor on ${cfg.port}`));
