/* FlightTrackr complete product layer: ticket scan, country insights, frequent-traveller cockpit */
(()=>{
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const uid=p=>`${p}_${crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random()}`;
  const normCode=v=>String(v||'').trim().toUpperCase();
  const addStyle=()=>{const s=document.createElement('style');s.textContent=`
  .ft-complete-panel{position:fixed;right:18px;bottom:18px;z-index:850;display:flex;gap:8px;flex-wrap:wrap;max-width:420px}.ft-complete-btn{border:1px solid #d7dee8;background:#fff;color:#06295a;border-radius:999px;padding:10px 13px;font-size:10px;font-weight:900;letter-spacing:.04em;box-shadow:0 8px 28px rgba(0,0,0,.12);cursor:pointer}.ft-complete-btn:hover{border-color:#d4a52c}.ft-modal{position:fixed;inset:0;z-index:1500;background:rgba(3,15,34,.6);display:flex;align-items:center;justify-content:center;padding:18px}.ft-card{width:min(820px,96vw);max-height:92vh;overflow:auto;background:#fff;border-radius:16px;box-shadow:0 30px 90px rgba(0,0,0,.35)}.ft-head{display:flex;justify-content:space-between;gap:14px;padding:18px 20px;border-bottom:1px solid #e6ebf1}.ft-head h2{margin:2px 0;color:#06295a}.ft-close{border:0;background:#f1f4f8;border-radius:50%;width:34px;height:34px;font-size:20px;cursor:pointer}.ft-body{padding:20px}.ft-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.ft-kpi{border:1px solid #e3e8ef;border-radius:10px;padding:12px;background:#f7f9fb}.ft-kpi strong{display:block;font-size:22px;color:#06295a}.ft-kpi span{font-size:9px;color:#657285;text-transform:uppercase;font-weight:900;letter-spacing:.06em}.ft-field{display:grid;gap:5px;margin:9px 0}.ft-field label{font-size:9px;font-weight:900;color:#657285;text-transform:uppercase}.ft-field input,.ft-field select,.ft-field textarea{padding:10px;border:1px solid #d8e0ea;border-radius:8px;font:inherit}.ft-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:16px}.ft-primary{border:0;background:#06295a;color:#fff;border-radius:8px;padding:10px 14px;font-weight:900;cursor:pointer}.ft-secondary{border:1px solid #d8e0ea;background:#fff;color:#06295a;border-radius:8px;padding:10px 14px;font-weight:900;cursor:pointer}.ft-result{margin-top:14px;padding:12px;border:1px dashed #cbd5e1;border-radius:8px;background:#f8fafc;font-size:11px;white-space:pre-wrap}.ft-progress{height:10px;background:#e8edf3;border-radius:999px;overflow:hidden}.ft-progress>span{display:block;height:100%;background:#d4a52c}.ft-country-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:8px}.ft-country{border:1px solid #e3e8ef;border-radius:9px;padding:10px;cursor:pointer}.ft-country strong{color:#06295a;display:block}.ft-muted{color:#657285;font-size:10px}.ft-preview{max-width:100%;max-height:360px;border-radius:10px;border:1px solid #e3e8ef}.ft-note{font-size:10px;color:#657285;margin-top:8px}@media(max-width:640px){.ft-grid{grid-template-columns:1fr 1fr}.ft-complete-panel{left:12px;right:12px;bottom:12px}.ft-complete-btn{flex:1}.ft-card{max-height:96vh}}`;document.head.appendChild(s)};
  function modal(title,sub,body){const root=document.createElement('div');root.className='ft-modal';root.innerHTML=`<div class="ft-card"><div class="ft-head"><div><div class="eyebrow">FLIGHTTRACKR</div><h2>${esc(title)}</h2><div class="ft-muted">${esc(sub||'')}</div></div><button class="ft-close" aria-label="Schließen">×</button></div><div class="ft-body">${body}</div></div>`;document.body.appendChild(root);root.querySelector('.ft-close').onclick=()=>root.remove();root.onclick=e=>{if(e.target===root)root.remove()};return root}
  function parseTicket(text){const t=String(text||'').replace(/\r/g,'\n').toUpperCase();const airports=[...t.matchAll(/\b([A-Z]{3})\s*(?:→|->|–|—|-|TO)\s*([A-Z]{3})\b/g)][0];const flight=[...t.matchAll(/\b([A-Z0-9]{2,3})\s?(\d{1,4}[A-Z]?)\b/g)].map(m=>m[1]+m[2]).find(v=>/^[A-Z]{1,3}\d/.test(v));const seat=(t.match(/\b(?:SEAT|SITZ)\s*[:#-]?\s*([0-9]{1,2}[A-Z])\b/)||[])[1]||'';const date=(t.match(/\b(\d{1,2}[.\/-]\d{1,2}[.\/-](?:20)?\d{2})\b/)||[])[1]||'';const cabin=(t.match(/\b(FIRST|BUSINESS|PREMIUM ECONOMY|ECONOMY)\b/)||[])[1]||'';return{origin:airports?.[1]||'',destination:airports?.[2]||'',flightNumber:flight||'',seat,cabin,date,raw:t}}
  async function scanTicket(){const el=modal('Flugticket scannen','Foto, Screenshot oder Boarding Pass auswählen. Verarbeitung erfolgt lokal im Browser.',`<div class="ft-field"><label>Datei auswählen</label><input id="ftScanFile" type="file" accept="image/*,application/pdf" capture="environment"></div><div id="ftScanPreview"></div><div class="ft-actions"><button class="ft-primary" id="ftStartScan">SCAN STARTEN</button></div><div class="ft-result" id="ftScanResult">Noch kein Scan durchgeführt.</div><div class="ft-note">Barcode-Erkennung wird zuerst versucht; anschließend kann OCR mit der vorhandenen lokalen OCR-Bibliothek laufen. Vor dem Speichern werden alle Werte bestätigt.</div>`);
    const file=el.querySelector('#ftScanFile'),preview=el.querySelector('#ftScanPreview'),result=el.querySelector('#ftScanResult');
    file.onchange=()=>{const f=file.files?.[0];if(f&&f.type.startsWith('image/')){const u=URL.createObjectURL(f);preview.innerHTML=`<img class="ft-preview" src="${u}" alt="Ticketvorschau">`}}
    el.querySelector('#ftStartScan').onclick=async()=>{const f=file.files?.[0];if(!f){result.textContent='Bitte zuerst ein Ticketbild auswählen.';return}if(!f.type.startsWith('image/')){result.textContent='PDF-Textimport ist in dieser Browser-Version noch nicht direkt verfügbar. Bitte PDF als Bild/Screenshot importieren.';return}result.textContent='Ticket wird analysiert …';let text='';try{if('BarcodeDetector'in window){const detector=new BarcodeDetector({formats:['qr_code','pdf417','aztec','data_matrix']});const bitmap=await createImageBitmap(f);const codes=await detector.detect(bitmap);text+=codes.map(c=>c.rawValue).join('\n')} }catch{}try{if(window.Tesseract){const out=await Tesseract.recognize(f,'eng+deu',{logger:()=>{}});text+='\n'+(out.data?.text||'')}}catch(e){text+='\n'}const p=parseTicket(text);result.innerHTML=`<strong>Erkannte Daten</strong><br>Flug: ${esc(p.flightNumber||'—')}<br>Route: ${esc(p.origin||'—')} → ${esc(p.destination||'—')}<br>Datum: ${esc(p.date||'—')}<br>Sitz: ${esc(p.seat||'—')}<br>Kabine: ${esc(p.cabin||'—')}<div class="ft-actions"><button class="ft-primary" id="ftCreateFromScan">ALS FLUG ÜBERNEHMEN</button></div>`;result.querySelector('#ftCreateFromScan').onclick=()=>{if(typeof form==='function'){el.remove();form(undefined,{origin:p.origin,destination:p.destination,flightNumber:p.flightNumber,seat:p.seat,cabin:p.cabin,comment:'Aus Ticketscan erkannt'})}else{const fs=typeof flights!=='undefined'?flights:[];fs.push({id:uid('scan'),date:'',origin:p.origin,destination:p.destination,airline:'',flightNumber:p.flightNumber,seat:p.seat,cabin:p.cabin,source:'ticket_scan',status:'planned',comment:'Aus Ticketscan erkannt'});if(typeof save==='function')save();location.reload()}}}
  }
  function countryDashboard(){const fs=typeof flights!=='undefined'?flights:[];const seen={};fs.forEach(f=>[f.origin,f.destination].forEach(a=>{const c=(typeof COUNTRY_BY_AIRPORT!=='undefined'&&COUNTRY_BY_AIRPORT[a])||'';if(c){seen[c]??={flights:0,airports:new Set()};seen[c].flights++;seen[c].airports.add(a)}}));const body=Object.entries(seen).sort((a,b)=>b[1].flights-a[1].flights).map(([c,v])=>`<div class="ft-country" data-country="${esc(c)}"><strong>${esc((typeof COUNTRY_NAMES!=='undefined'&&COUNTRY_NAMES[c])||c)}</strong><span class="ft-muted">${v.airports.size} Flughäfen · ${v.flights} Flugbewegungen</span></div>`).join('');const el=modal('Besuchte Länder','Deine persönliche Reisehistorie nach Ländern.',`<div class="ft-grid"><div class="ft-kpi"><strong>${Object.keys(seen).length}</strong><span>Länder</span></div><div class="ft-kpi"><strong>${new Set(fs.flatMap(f=>[f.origin,f.destination])).size}</strong><span>Flughäfen</span></div><div class="ft-kpi"><strong>${fs.length}</strong><span>Flüge</span></div></div><h3>Besuchte Länder</h3><div class="ft-country-list">${body||'<div class="ft-muted">Noch keine Länder erkannt.</div>'}</div>`);el.querySelectorAll('[data-country]').forEach(b=>b.onclick=()=>{if(window.FlightTrackrExplorer?.openCountry){el.remove();window.FlightTrackrExplorer.openCountry(b.dataset.country)}})}
  function milesDashboard(){const fs=typeof flights!=='undefined'?flights:[];const actual=fs.reduce((n,f)=>n+(Number(f.statusPoints)||Number(f.qualifyingPoints)||0),0);const targets=[['Frequent Traveller',650],['Senator',2000],['HON Circle',6000]];const cards=targets.map(([n,t])=>`<div class="ft-kpi"><strong>${actual}</strong><span>${esc(n)} / ${t} Points</span><div class="ft-progress"><span style="width:${Math.min(100,actual/t*100)}%"></span></div></div>`).join('');modal('Frequent Traveller Cockpit','Statusfortschritt wird aus den in FlightTrackr gespeicherten Points berechnet.',`<div class="ft-grid">${cards}</div><div class="ft-note">Points können pro Flug manuell gepflegt werden. Eine automatische Konto-Synchronisierung wird bewusst nicht per Scraping implementiert.</div>`)}
  function install(){addStyle();const panel=document.createElement('div');panel.className='ft-complete-panel';panel.innerHTML='<button class="ft-complete-btn" data-ft="scan">TICKET SCANNEN</button><button class="ft-complete-btn" data-ft="countries">LÄNDER</button><button class="ft-complete-btn" data-ft="miles">STATUS</button>';document.body.appendChild(panel);panel.querySelector('[data-ft="scan"]').onclick=scanTicket;panel.querySelector('[data-ft="countries"]').onclick=countryDashboard;panel.querySelector('[data-ft="miles"]').onclick=milesDashboard}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
