function createTripUI(){
  const list=[...filtered()].slice(0,40);
  modal('Neue Reise',`<form id="tripForm"><div class="form-field"><label>Reisename</label><input name="name" required placeholder="z. B. Bangkok 2026" /></div><div style="margin-top:14px;display:grid;gap:6px">${list.map(f=>`<label style="display:grid;grid-template-columns:22px 1fr;align-items:center;border:1px solid var(--line);border-radius:6px;padding:8px;font-size:10px"><input type="checkbox" name="flightIds" value="${esc(f.id)}" /><span>${esc(displayDate(f.date))} · <strong>${esc(f.origin)} → ${esc(f.destination)}</strong> · ${esc(f.flightNumber||'—')} · ${esc(f.airline||'')}</span></label>`).join('')}</div><div class="form-actions"><button type="button" class="btn btn-secondary" data-action="close-modal">Abbrechen</button><button class="btn btn-primary">Reise speichern</button></div></form>`,m=>$('#tripForm',m).onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target);const name=String(fd.get('name')||'').trim();const ids=fd.getAll('flightIds');if(!name||!ids.length){alert('Bitte Name und mindestens einen Flug auswählen.');return}trips.push({id:uid('trip'),name,flightIds:ids,createdAt:new Date().toISOString()});save();closeModal();renderAll();alert(`Reise „${name}“ angelegt.`)})
}
function exportTripsJSON(){const payload=trips.map(t=>({...t,flights:t.flightIds.map(id=>flights.find(f=>f.id===id)).filter(Boolean)}));download('flighttrackr-trips.json',JSON.stringify(payload,null,2),'application/json')}
document.body.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(!a)return;const x=a.dataset.action;if(x==='create-trip')createTripUI();if(x==='export-json')exportJSON();if(x==='export-csv')exportCSV();if(x==='export-xlsx')exportXLSX();if(x==='export-trips')exportTripsJSON()});

/* Rich country information and reliable clickable airport/country routing. */
(()=>{
  let airportsMeta={},countriesMeta={};
  const esc2=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  Promise.all([fetch('data/airports.json',{cache:'no-store'}).then(r=>r.ok?r.json():{}),fetch('data/countries.json',{cache:'no-store'}).then(r=>r.ok?r.json():{})]).then(([a,c])=>{airportsMeta=a;countriesMeta=c}).catch(()=>{});
  const countryFor=a=>airportsMeta[a]?.countryCode||COUNTRY_BY_AIRPORT?.[a]||'';
  function closeInfo(root){root.remove()}
  function info(title,subtitle,body){const root=document.createElement('div');root.className='info-modal';root.innerHTML=`<div class="info-card"><div class="info-head"><div><div class="eyebrow">FLIGHTTRACKR EXPLORER</div><h2>${esc2(title)}</h2><div class="info-sub">${esc2(subtitle)}</div></div><button class="info-close">×</button></div><div class="info-body">${body}</div></div>`;document.body.appendChild(root);root.querySelector('.info-close').onclick=()=>closeInfo(root);root.onclick=e=>{if(e.target===root)closeInfo(root)};return root}
  function openCountryInfo(code){const meta=countriesMeta[code]||{name:COUNTRY_NAMES?.[code]||code};const fs=(flights||[]).filter(f=>countryFor(f.origin)===code||countryFor(f.destination)===code);const aps=[...new Set(fs.flatMap(f=>[f.origin,f.destination]).filter(a=>countryFor(a)===code))].sort();const airlines=[...new Set(fs.map(f=>f.airline).filter(Boolean))];const dates=fs.map(f=>f.date).filter(Boolean).sort();const facts=[['Hauptstadt',meta.capital],['Kontinent',meta.continent],['Währung',meta.currency],['Sprache',meta.language]].filter(x=>x[1]).map(([k,v])=>`<div class="country-flight"><strong>${esc2(k)}</strong><span>${esc2(v)}</span></div>`).join('');const airports=aps.map(a=>`<button class="airport-chip" data-open-airport="${esc2(a)}">${esc2(a)} <span>${esc2(airportsMeta[a]?.city||'')}</span></button>`).join('')||'<div class="info-sub">Keine Flughäfen.</div>';const recent=fs.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,25).map(f=>`<div class="country-flight"><span><strong>${esc2(f.flightNumber||'—')}</strong> · ${esc2(f.origin)} → ${esc2(f.destination)}</span><span>${esc2(f.date||'')}</span></div>`).join('');const root=info(meta.name,`${code} · besucht`, `<div class="info-kpis"><div class="info-kpi"><strong>${aps.length}</strong><span>Flughäfen</span></div><div class="info-kpi"><strong>${fs.length}</strong><span>Flüge</span></div><div class="info-kpi"><strong>${airlines.length}</strong><span>Airlines</span></div><div class="info-kpi"><strong>${dates[0]||'—'}</strong><span>erster Besuch</span></div></div><h3>Länderinfos</h3>${facts||'<div class="info-sub">Basisinformationen verfügbar.</div>'}<h3 style="margin-top:18px">Besuchte Flughäfen</h3><div>${airports}</div><h3 style="margin-top:18px">Letzter Besuch</h3><div class="country-flight"><strong>Datum</strong><span>${esc2(dates.at(-1)||'—')}</span></div><h3 style="margin-top:18px">Flugchronik</h3>${recent||'<div class="info-sub">Keine Flüge gespeichert.</div>'}`);root.querySelectorAll('[data-open-airport]').forEach(b=>b.onclick=()=>{const code=b.dataset.openAirport;root.remove();window.FlightTrackrExplorer?.openAirport?.(code)})}
  document.addEventListener('click',e=>{const c=e.target.closest('[data-open-country]');if(c){e.preventDefault();e.stopImmediatePropagation();openCountryInfo(c.dataset.openCountry)}},true);
})();
